In [4]:
#program for matrix multiplication

import numpy as np
array1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print("matrix 1: \n",array1)

array2=np.array([10,11,12,13,14,15,16,17,18]).reshape(3,3)
print("matrix 2: \n",array2)

mul=np.dot(array1,array2)
print("Dot product:\n\n",mul)

transpose=mul.transpose()
print("\n transpose matrix is :\n\n",transpose)


matrix 1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix 2: 
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Dot product:

 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]

 transpose matrix is :

 [[ 84 201 318]
 [ 90 216 342]
 [ 96 231 366]]
