In [2]:
#svd

import numpy as np
from scipy.linalg import svd

array1=np.array([2,3,4,5,6,7,8,9,0]).reshape(3,3)
a,b,c=svd(array1)
print("decomposed arrays:\n")
print(a)
print("\n\n",b)
print("\n\n",c)

print("Reconstructed array:\n")

e=(a @ np.diag(b) @ c)
new_array=e.astype('i')
print("\n\n",new_array)

decomposed arrays:

[[-0.30491383 -0.39796963 -0.86524432]
 [-0.62566615 -0.60125012  0.49703135]
 [-0.71803163  0.69290582 -0.06566665]]


 [15.65784686  6.22391082  0.30784057]


 [[-0.60560124 -0.71089104 -0.35760462]
 [ 0.27973677  0.2305211  -0.93199108]
 [ 0.74497952 -0.66445011  0.0592585 ]]
Reconstructed array:



 [[1 2 3]
 [4 5 6]
 [7 8 0]]
